### ISSUE TITLE
[i18n] Dates also in portuguese

### ISSUE THREAD

**Issue by fititnt** [woliveiras/__s#4]
By default Jekyll have only dates in english. But is possible make it work also with dates.

See https://github.com/webiwg/acessibilidade-web-pt/blob/master/_includes/date-portugues.html

``` html
{% assign m = include.date | date: "%-m" %}
{{ include.date | date: "%-d" }} de
{% case m %}
  {% when '1' %}Janeiro
  {% when '2' %}Fevereiro
  {% when '3' %}Março
  {% when '4' %}Abril
  {% when '5' %}Maio
  {% when '6' %}Junho
  {% when '7' %}Julho
  {% when '8' %}Agosto
  {% when '9' %}Setembro
  {% when '10' %}Outubro
  {% when '11' %}Novembro
  {% when '12' %}Dezembro
{% endcase %} de
{{ include.date | date: "%Y" }}
```

This was used on my comment in https://github.com/woliveiras/__s/issues/2#issuecomment-246105319

**Comment by woliveiras** [comment]
Great!

I did a schema on [_config.yml](https://github.com/woliveiras/__s/blob/master/_config.yml#L16) based on [this](https://github.com/vivadecora/vivadecora.github.io/blob/master/_config.yml#L114) and use [like this](https://github.com/woliveiras/__s/blob/master/index.html#L29).

Do you enjoy this scheme?

**Comment by fititnt** [comment]
Better than I would suggest

**Comment by woliveiras** [comment]
\o/

Great!

I will close this issue, OK?
